# Generated by Django 3.1.3 on 2020-11-12 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_auto_20201112_1113'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
