# Generated by Django 3.1.3 on 2020-11-13 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_review_comment'),
        ('account', '0003_auto_20201112_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_you',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='you_expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.category'),
        ),
    ]
