# Generated by Django 3.1.3 on 2020-11-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('courses_category', '0001_initial'),
        ('account', '0005_auto_20201112_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='your_expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='courses_category.category'),
        ),
    ]
