# Generated by Django 3.1.3 on 2021-07-25 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('consulting', '0002_auto_20210725_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='tel',
            field=models.CharField(max_length=11, unique=True,
                                   validators=[django.core.validators.RegexValidator(regex='^09[0-9]{9}')]),
        ),
    ]
