# Generated by Django 4.0 on 2021-12-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0004_alter_consulting_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='tel',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
