# Generated by Django 4.0 on 2021-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0006_alter_consulting_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
