# Generated by Django 3.1.3 on 2020-11-11 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created',), 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created',
                                    to=settings.AUTH_USER_MODEL, verbose_name='مدرس'),
        ),
    ]
