# Generated by Django 3.1.3 on 2020-11-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0003_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.FloatField(null=True),
        ),
    ]
