# Generated by Django 3.1.3 on 2020-11-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201112_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
