# Generated by Django 3.1.3 on 2020-11-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0005_auto_20201112_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
