# Generated by Django 3.1.3 on 2020-11-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0008_auto_20201112_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='url',
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True),
        ),
    ]
