# Generated by Django 3.1.3 on 2020-11-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201112_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='duration',
            field=models.TextField(null=True),
        ),
    ]
