# Generated by Django 3.1.3 on 2020-11-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0011_auto_20201113_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
