# Generated by Django 3.1.3 on 2020-11-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20201119_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
