# Generated by Django 3.1.3 on 2020-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_auto_20201119_0526'),
        ('courses_category', '0001_initial'),
        ('courses', '0013_auto_20201119_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(null=True, to='courses_category.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
